// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Quality_Management.DataAccess;

#nullable disable

namespace Quality_Management.Migrations
{
    [DbContext(typeof(QualityManagementDbContext))]
    [Migration("20241104025712_Create Procedure table")]
    partial class CreateProceduretable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Quality_Management.Model.Procedure", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("OfficeId")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("nvarchar(8)")
                        .HasColumnName("office");

                    b.Property<long>("PlaceNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("place_number");

                    b.Property<DateTime>("ProcedureEnd")
                        .HasColumnType("datetime2")
                        .HasColumnName("procedure_end");

                    b.Property<DateTime>("ProcedureStart")
                        .HasColumnType("datetime2")
                        .HasColumnName("procedure_start");

                    b.HasKey("Id");

                    b.ToTable("Procedures");
                });
#pragma warning restore 612, 618
        }
    }
}
